# -*- coding: utf-8 -*-
"""NYC Taxi Demand Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10orH6Ob9i_ZG461Bsvj5F_QEDzHDvkIo
"""

import pandas as pd
import matplotlib.pyplot as plt

# NYC Taxi demand dataset
url = "https://raw.githubusercontent.com/numenta/NAB/master/data/realKnownCause/nyc_taxi.csv"
df = pd.read_csv(url, parse_dates=["timestamp"],index_col='timestamp')
df.columns = ["demand"]

df

# Explore
print("Total records :", len(df))
print("Date range    :", df.index.min(), "to", df.index.max())
print("Missing values:", df.isnull().sum()[0])
print("\nBasic statistics:")
print(df.describe())

# Plot full series
plt.figure(figsize=(14, 4))
plt.plot(df["demand"], color="steelblue", linewidth=0.8)
plt.title("NYC Taxi Demand Over Time")
plt.ylabel("Number of Trips")
plt.xlabel("Date")
plt.tight_layout()
plt.savefig("day1_full.png")
plt.show()

# Plot just one week to see daily pattern
one_week = df.iloc[:336]  # 48 readings per day x 7 days
plt.figure(figsize=(14, 4))
plt.plot(one_week["demand"], color="darkorange", linewidth=1)
plt.title("NYC Taxi Demand — First Week (Pattern View)")
plt.ylabel("Number of Trips")
plt.xlabel("Date")
plt.tight_layout()
plt.savefig("day1_week.png")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ── TRAIN/TEST SPLIT ──────────────────────────
# Last 30 days = test, everything before = train
split = df.index.max() - pd.Timedelta(days=30)
train = df[df.index <= split]
test  = df[df.index > split]

print(f"Train size: {len(train)} records")
print(f"Test size : {len(test)} records")

# ── RANDOM WALK FORECAST ──────────────────────
# Predict = previous value
test = test.copy()
test["predicted"] = test["demand"].shift(1)
test = test.dropna()

# ── EVALUATE ──────────────────────────────────
actual    = test["demand"].values
predicted = test["predicted"].values

mae  = mean_absolute_error(actual, predicted)
rmse = np.sqrt(mean_squared_error(actual, predicted))

print(f"\nRandom Walk Results:")
print(f"MAE  : {mae:.0f} trips")
print(f"RMSE : {rmse:.0f} trips")

# ── PLOT ──────────────────────────────────────
plt.figure(figsize=(14, 4))
plt.plot(test["demand"].values[:200],
         label="Actual",    color="black",     linewidth=1)
plt.plot(test["predicted"].values[:200],
         label="Predicted", color="steelblue", linewidth=1, linestyle="--")
plt.title("Random Walk Forecast — NYC Taxi Demand")
plt.ylabel("Number of Trips")
plt.xlabel("Time Steps")
plt.legend()
plt.tight_layout()
plt.savefig("day2_random_walk.png")
plt.show()

# ── ADD FEATURES ──────────────────────────────

# Time-based features (patterns you already spotted)
df["hour"]        = df.index.hour
df["day_of_week"] = df.index.dayofweek  # 0=Monday, 6=Sunday
df["is_weekend"]  = (df.index.dayofweek >= 5).astype(int)

# Lag features (past demand values as input)
df["lag_1"]  = df["demand"].shift(1)   # 30 mins ago
df["lag_2"]  = df["demand"].shift(2)   # 1 hour ago
df["lag_48"] = df["demand"].shift(48)  # Same time yesterday

# Rolling average (recent trend)
df["rolling_mean_8"] = df["demand"].shift(1).rolling(8).mean()

# Drop rows with missing values from lag/rolling
df = df.dropna()

df

print("Features created successfully")
print(f"Shape: {df.shape}")
print(f"\nFirst row of features:")
print(df.iloc[0])

import matplotlib.pyplot as plt

day_avg = df.groupby("day_of_week")["demand"].mean()
print(day_avg)  # Let's see what values we get first

days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

plt.figure(figsize=(7, 4))
plt.plot(range(7), day_avg.values, color="darkorange", marker="o")
plt.xticks(range(7), days)
plt.title("Average Demand by Day of Week")
plt.ylabel("Average Trips")
plt.tight_layout()
plt.show()

from sklearn.linear_model import LinearRegression

split = df.index.max() - pd.Timedelta(days=30)
train = df[df.index <= split]
test  = df[df.index > split]

feature_cols = ["hour", "day_of_week", "is_weekend",
                "lag_1", "lag_2", "lag_48", "rolling_mean_8"]

X_train = train[feature_cols]
y_train = train["demand"]
X_test  = test[feature_cols]
y_test  = test["demand"]

print(f"Train size: {len(train)}")
print(f"Test size : {len(test)}")

# ── TRAIN MODEL ───────────────────────────────
model = LinearRegression()
model.fit(X_train, y_train)
print("\nModel trained successfully")

# ── PREDICT ───────────────────────────────────
predictions = model.predict(X_test)

# ── EVALUATE ──────────────────────────────────
mae  = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print(f"\nLinear Regression Results:")
print(f"MAE  : {mae:.0f} trips")
print(f"RMSE : {rmse:.0f} trips")

print(f"\nRandom Walk Results (baseline):")
print(f"MAE  : 1256 trips")
print(f"RMSE : 1646 trips")

improvement_mae  = ((1256 - mae) / 1256) * 100
improvement_rmse = ((1646 - rmse) / 1646) * 100
print(f"\nImprovement over Random Walk:")
print(f"MAE  improved by: {improvement_mae:.1f}%")
print(f"RMSE improved by: {improvement_rmse:.1f}%")

# ── PLOT ──────────────────────────────────────
plt.figure(figsize=(14, 4))
plt.plot(y_test.values[:200],
         label="Actual",    color="black",     linewidth=1)
plt.plot(predictions[:200],
         label="Predicted", color="steelblue", linewidth=1, linestyle="--")
plt.title("Linear Regression Forecast — NYC Taxi Demand")
plt.ylabel("Number of Trips")
plt.xlabel("Time Steps")
plt.legend()
plt.tight_layout()
plt.savefig("day4_linear_regression.png")
plt.show()

